### ISSUE TITLE
Jump to job does not always work

### ISSUE THREAD

**Issue by loewenstein** [danhigham/concourse-vis#4]
Steps to reproduce:
1. Open pipeline yml
1. Open pipeline pane
1. Click on any job on the pipeline pane

Expected:
pipeline source editor jumps to job definition

Actual:
Nothing happens.

Workaround:
Click into editor and back into pipeline pane.
Now Job selection works.

Note: Maybe related, if you edit something in the pipeline sources jump to job works only after you switched focus again, i.e. click pane, click source, click pane again.

**Comment by danhigham** [comment]
Fixed in commit e61951373c9ba2858bf0e4f2ad709a463ad8dac2
