### ISSUE TITLE
Uncaught TypeError: Cannot read property 'slice' of undefined

### ISSUE THREAD

**Issue by kdvolder** [danhigham/concourse-vis#5]
[Enter steps to reproduce:]

1. Open a concourse pipeline file
2. CTRL-ALT-P
3. Click on any box in the visualizer pane

**Atom**: 1.19.2 x64
**Electron**: 1.6.9
**OS**: Ubuntu 14.04.5
**Thrown From**: [concourse-vis](https://github.com/danhigham/concourse-vis) package 1.4.0

### Stack Trace

Uncaught TypeError: Cannot read property 'slice' of undefined

```
At /home/kdvolder/.atom/packages/concourse-vis/lib/concourse-vis.js:54

TypeError: Cannot read property 'slice' of undefined
    at /packages/concourse-vis/lib/concourse-vis.js:54:33)
    at SVGAElement.dispatch (/packages/concourse-vis/node_modules/jquery/dist/jquery.js:4409:9)
    at SVGAElement.elemData.handle (/packages/concourse-vis/node_modules/jquery/dist/jquery.js:4095:28)
```

### Commands

```
     -0:06.2.0 datatip:toggle (input.hidden-input)
     -0:06.0 concourse-vis:toggle (input.hidden-input)
```

### Non-Core Packages

```
atom-ide-ui 0.1.11 
cf-manifest-yaml 0.0.9 
concourse-pipeline-yaml 0.0.9 
concourse-vis 1.4.0 
```

**Comment by EugenMayer** [comment]
Same here, any change this gets fixed?

**Comment by danhigham** [comment]
Hey, fixed this sorry for the delay. I'm going to look at updating this plugin to bring it up to date with the current Concourse UI
