### ISSUE TITLE
Still active? New Ownership?

### ISSUE THREAD

**Issue by DerpTwerp** [danhigham/concourse-vis#6]
So I see the last update for this code was about 2 years ago and there are new issues being reported. Has this project been abandoned? If so, would the owner be willing to give up ownership?
I would hate to make a fork of this and try to get things fixed and delivered to the masses if the original owner intends to keep things up.

**Comment by danhigham** [comment]
Hello DerpTwerp! I spent a couple of hours fixing the current version up but it really needs a bit of a re-write, I pulled the visual stuff from concourse a long time ago and it's changed a lot since then. For now though, it's working fine.

**Comment by danhigham** [comment]
I'm going to close this for now. Please re-open if you wish to continue the conversation.
