### ISSUE TITLE
Hangups in Atom for OSX

### ISSUE THREAD

**Issue by vanceric** [danhigham/concourse-vis#7]
Any time I use concourse-vis in atom for OSX I get hangups within about 3-5 minutes. I haven't been able to run down the cause, but restarting atom seems to resolve the issue. Wonderful tool otherwise, any ideas on how to troubleshoot?

**Comment by danhigham** [comment]
Greetings, I did address some of these kinds of issues in the last release. Are you sure you have the latest version installed.

**Comment by vanceric** [comment]
That's it! Not sure how I was on an older version since I had re-installed a few times, but updating to 1.4.3 sorted it out. Left it running overnight and no hang-ups at all. Most helpful CI tool in existence.

**Comment by danhigham** [comment]
Awww man, thanks for the props! Makes it all worth while :-)
